version: '2.2'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: cards
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
      
  logic-ea:
    container_name: logic-ea
    image: logic-ea
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev

