spring:
  datasource:
    url: jdbc:h2:mem:test_card
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: "classpath:/migrations/changelog.xml"
    database-change-log-table: test_cards_migration
    database-change-log-lock-table: test_cards_migration_lock
    clear-checksums: ${CLEAR_CHECKSUM:false}
    rollback-file: log/cards.rollback.sql
