spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/cards}
    username: ${DB_USER:root}
    password: ${DB_PASS:}

  liquibase:
    enabled: false
    change-log: "classpath:/migrations/changelog.xml"
    database-change-log-table: cards_migration
    database-change-log-lock-table: cards_migration_lock
    clear-checksums: ${CLEAR_CHECKSUM:false}
    rollback-file: log/cards.rollback.sql
