spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: "classpath:/migrations/changelog.xml"
    database-change-log-table: cards_migration
    database-change-log-lock-table: cards_migration_lock
    clear-checksums: ${CLEAR_CHECKSUM:false}
    rollback-file: log/cards.rollback.sql
